// Fonction helper pour construire les chemins des images
const getImageUrl = (modelName: string, colorCombination: string) => {
  return `/images/${modelName}_${colorCombination}.png`;
};

// Models avec les images locales
export const models = [
  {
    id: "otto-rosso",
    name: "Otto Rosso",
    image: "/images/Otto_Rosso_Rose_Rose.png",
    allowedColors: ["Rose", "Rose foncé", "Blanc", "Noir"],
    combos: {
      Rose: {
        Rose: getImageUrl("Otto_Rosso", "Rose_Rose"),
        "Rose foncé": getImageUrl("Otto_Rosso", "Rose_Rosefonce"),
        Blanc: getImageUrl("Otto_Rosso", "Rose_Blanc"),
        Noir: getImageUrl("Otto_Rosso", "Rose_Noir"),
      },
      "Rose foncé": {
        Rose: getImageUrl("Otto_Rosso", "Rosefonce_Rose"),
        "Rose foncé": getImageUrl("Otto_Rosso", "Rosefonce_Rosefonce"),
        Blanc: getImageUrl("Otto_Rosso", "Rosefonce_Blanc"),
        Noir: getImageUrl("Otto_Rosso", "Rosefonce_Noir"),
      },
      Blanc: {
        Rose: getImageUrl("Otto_Rosso", "Blanc_Rose"),
        "Rose foncé": getImageUrl("Otto_Rosso", "Blanc_Rosefonce"),
        Blanc: getImageUrl("Otto_Rosso", "Blanc_Blanc"),
        Noir: getImageUrl("Otto_Rosso", "Blanc_Noir"),
      },
      Noir: {
        Rose: getImageUrl("Otto_Rosso", "Noir_Rose"),
        "Rose foncé": getImageUrl("Otto_Rosso", "Noir_Rosefonce"),
        Blanc: getImageUrl("Otto_Rosso", "Noir_Blanc"),
        Noir: getImageUrl("Otto_Rosso", "Noir_Noir"),
      },
    },
    price: 60,
    discountedPrice: 60,
    description: "Montre de design premium avec coloris italiens",
    productHandle: "otto-rosso-cadran",
  },
  {
    id: "lan-ba",
    name: "Lân Bà",
    image: "/images/Lan_Ba_Cyan_Cyan.png",
    allowedColors: ["Blanc", "Marine", "Cyan", "Noir"],
    combos: {
      Blanc: {
        Blanc: getImageUrl("Lan_Ba", "Blanc_Blanc"),
        Marine: getImageUrl("Lan_Ba", "Blanc_Marine"),
        Cyan: getImageUrl("Lan_Ba", "Blanc_Cyan"),
        Noir: getImageUrl("Lan_Ba", "Blanc_Noir"),
      },
      Marine: {
        Blanc: getImageUrl("Lan_Ba", "Marine_Blanc"),
        Marine: getImageUrl("Lan_Ba", "Marine_Marine"),
        Cyan: getImageUrl("Lan_Ba", "Marine_Cyan"),
        Noir: getImageUrl("Lan_Ba", "Marine_Noir"),
      },
      Cyan: {
        Blanc: getImageUrl("Lan_Ba", "Cyan_Blanc"),
        Marine: getImageUrl("Lan_Ba", "Cyan_Marine"),
        Cyan: getImageUrl("Lan_Ba", "Cyan_Cyan"),
        Noir: getImageUrl("Lan_Ba", "Cyan_Noir"),
      },
      Noir: {
        Blanc: getImageUrl("Lan_Ba", "Noir_Blanc"),
        Marine: getImageUrl("Lan_Ba", "Noir_Marine"),
        Cyan: getImageUrl("Lan_Ba", "Noir_Cyan"),
        Noir: getImageUrl("Lan_Ba", "Noir_Noir"),
      },
    },
    price: 60,
    discountedPrice: 60,
    description: "Montre vietnamienne moderne",
    productHandle: "lan-ba-cadran",
  },
  {
    id: "green-eight",
    name: "Green Eight",
    image: "/images/Green_Eight_Vert_Vert.png",
    allowedColors: ["Blanc", "Noir", "Vert"],
    combos: {
      Blanc: {
        Blanc: getImageUrl("Green_Eight", "Blanc_Blanc"),
        Noir: getImageUrl("Green_Eight", "Blanc_Noir"),
        Vert: getImageUrl("Green_Eight", "Blanc_Vert"),
      },
      Noir: {
        Blanc: getImageUrl("Green_Eight", "Noir_Blanc"),
        Noir: getImageUrl("Green_Eight", "Noir_Noir"),
        Vert: getImageUrl("Green_Eight", "Noir_Vert"),
      },
      Vert: {
        Blanc: getImageUrl("Green_Eight", "Vert_Blanc"),
        Noir: getImageUrl("Green_Eight", "Vert_Noir"),
        Vert: getImageUrl("Green_Eight", "Vert_Vert"),
      },
    },
    price: 60,
    discountedPrice: 60,
    description: "Montre minimaliste écologique",
    productHandle: "green-eight-cadran",
  },
  {
    id: "ocho-negro",
    name: "Ocho Negro",
    image: "/images/Ocho_Negro_Rose_Blanc.png",
    allowedColors: ["Blanc", "Noir", "Rose", "Rose foncé", "Bleu ciel", "Bleu marine", "Vert", "Vert foncé", "Turquoise", "Rouge"],
    combos: {
      Blanc: {
        Blanc: getImageUrl("Ocho_Negro", "Blanc_Blanc"),
        Noir: getImageUrl("Ocho_Negro", "Blanc_Noir"),
        Rose: getImageUrl("Ocho_Negro", "Blanc_Rose"),
        "Rose foncé": getImageUrl("Ocho_Negro", "Blanc_Rosefonce"),
        "Bleu ciel": getImageUrl("Ocho_Negro", "Blanc_Bleuciel"),
        "Bleu marine": getImageUrl("Ocho_Negro", "Blanc_Bleumarine"),
        Vert: getImageUrl("Ocho_Negro", "Blanc_Vert"),
        "Vert foncé": getImageUrl("Ocho_Negro", "Blanc_Vertfonce"),
        Turquoise: getImageUrl("Ocho_Negro", "Blanc_Turquoise"),
        Rouge: getImageUrl("Ocho_Negro", "Blanc_Rouge"),
      },
      Noir: {
        Blanc: getImageUrl("Ocho_Negro", "Noir_Blanc"),
        Noir: getImageUrl("Ocho_Negro", "Noir_Noir"),
        Rose: getImageUrl("Ocho_Negro", "Noir_Rose"),
        "Rose foncé": getImageUrl("Ocho_Negro", "Noir_Rosefonce"),
        "Bleu ciel": getImageUrl("Ocho_Negro", "Noir_Bleuciel"),
        "Bleu marine": getImageUrl("Ocho_Negro", "Noir_Bleumarine"),
        Vert: getImageUrl("Ocho_Negro", "Noir_Vert"),
        "Vert foncé": getImageUrl("Ocho_Negro", "Noir_Vertfonce"),
        Turquoise: getImageUrl("Ocho_Negro", "Noir_Turquoise"),
        Rouge: getImageUrl("Ocho_Negro", "Noir_Rouge"),
      },
    },
    price: 60,
    discountedPrice: 60,
    description: "Montre très colorée avec 10 combinaisons",
    productHandle: "ocho-negro-cadran",
  },
  {
    id: "otg-roz",
    name: "OTG Roz",
    image: "/images/Otg_Roz_Turquoise_Turquoise.png",
    allowedColors: ["Blanc", "Noir", "Rose", "Turquoise", "Jaune"],
    combos: {
      Blanc: {
        Blanc: getImageUrl("Otg_Roz", "Blanc_Blanc"),
        Noir: getImageUrl("Otg_Roz", "Blanc_Noir"),
        Rose: getImageUrl("Otg_Roz", "Blanc_Rose"),
        Turquoise: getImageUrl("Otg_Roz", "Blanc_Turquoise"),
        Jaune: getImageUrl("Otg_Roz", "Blanc_Jaune"),
      },
      Noir: {
        Blanc: getImageUrl("Otg_Roz", "Noir_Blanc"),
        Noir: getImageUrl("Otg_Roz", "Noir_Noir"),
        Rose: getImageUrl("Otg_Roz", "Noir_Rose"),
        Turquoise: getImageUrl("Otg_Roz", "Noir_Turquoise"),
        Jaune: getImageUrl("Otg_Roz", "Noir_Jaune"),
      },
      Rose: {
        Blanc: getImageUrl("Otg_Roz", "Rose_Blanc"),
        Noir: getImageUrl("Otg_Roz", "Rose_Noir"),
        Rose: getImageUrl("Otg_Roz", "Rose_Rose"),
        Turquoise: getImageUrl("Otg_Roz", "Rose_Turquoise"),
        Jaune: getImageUrl("Otg_Roz", "Rose_Jaune"),
      },
      Turquoise: {
        Blanc: getImageUrl("Otg_Roz", "Turquoise_Blanc"),
        Noir: getImageUrl("Otg_Roz", "Turquoise_Noir"),
        Rose: getImageUrl("Otg_Roz", "Turquoise_Rose"),
        Turquoise: getImageUrl("Otg_Roz", "Turquoise_Turquoise"),
        Jaune: getImageUrl("Otg_Roz", "Turquoise_Jaune"),
      },
      Jaune: {
        Blanc: getImageUrl("Otg_Roz", "Jaune_Blanc"),
        Noir: getImageUrl("Otg_Roz", "Jaune_Noir"),
        Rose: getImageUrl("Otg_Roz", "Jaune_Rose"),
        Turquoise: getImageUrl("Otg_Roz", "Jaune_Turquoise"),
        Jaune: getImageUrl("Otg_Roz", "Jaune_Jaune"),
      },
    },
    price: 60,
    discountedPrice: 60,
    description: "Montre rose et turquoise vibrant",
    productHandle: "otg-roz-cadran",
  },
  {
    id: "blaue-acht",
    name: "Blaue Acht",
    image: "/images/Blaue_Acht_Bleuciel_Bleuciel.png",
    allowedColors: ["Blanc", "Noir", "Bleu ciel", "Vert pâle"],
    combos: {
      Blanc: {
        Blanc: getImageUrl("Blaue_Acht", "Blanc_Blanc"),
        Noir: getImageUrl("Blaue_Acht", "Blanc_Noir"),
        "Bleu ciel": getImageUrl("Blaue_Acht", "Blanc_Bleuciel"),
        "Vert pâle": getImageUrl("Blaue_Acht", "Blanc_Vertpale"),
      },
      Noir: {
        Blanc: getImageUrl("Blaue_Acht", "Noir_Blanc"),
        Noir: getImageUrl("Blaue_Acht", "Noir_Noir"),
        "Bleu ciel": getImageUrl("Blaue_Acht", "Noir_Bleuciel"),
        "Vert pâle": getImageUrl("Blaue_Acht", "Noir_Vertpale"),
      },
      "Bleu ciel": {
        Blanc: getImageUrl("Blaue_Acht", "Bleuciel_Blanc"),
        Noir: getImageUrl("Blaue_Acht", "Bleuciel_Noir"),
        "Bleu ciel": getImageUrl("Blaue_Acht", "Bleuciel_Bleuciel"),
        "Vert pâle": getImageUrl("Blaue_Acht", "Bleuciel_Vertpale"),
      },
      "Vert pâle": {
        Blanc: getImageUrl("Blaue_Acht", "Vertpale_Blanc"),
        Noir: getImageUrl("Blaue_Acht", "Vertpale_Noir"),
        "Bleu ciel": getImageUrl("Blaue_Acht", "Vertpale_Bleuciel"),
        "Vert pâle": getImageUrl("Blaue_Acht", "Vertpale_Vertpale"),
      },
    },
    price: 60,
    discountedPrice: 60,
    description: "Montre bleu et vert pastel allemande",
    productHandle: "blaue-acht-cadran",
  },
  {
    id: "orenji-hachi",
    name: "Orenji Hachi",
    image: "/images/Orenji_Hachi_Orange_Orange.png",
    allowedColors: ["Orange"],
    combos: {
      Orange: {
        Orange: getImageUrl("Orenji_Hachi", "Orange_Orange"),
      },
    },
    price: 60,
    discountedPrice: 60,
    description: "Montre orange minimaliste japonaise",
    productHandle: "orenji-hachi-cadran",
  },
  {
    id: "huit-blanc",
    name: "Huit Blanc",
    image: "/images/Huit_Blanc_Blanc_Blanc.png",
    allowedColors: ["Blanc"],
    combos: {
      Blanc: {
        Blanc: getImageUrl("Huit_Blanc", "Blanc_Blanc"),
      },
    },
    price: 60,
    discountedPrice: 60,
    description: "Montre minimaliste blanche pure",
    productHandle: "huit-blanc-cadran",
  },
];
